name: healthmate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cupertino_icons: ^1.0.8
  cloud_firestore: ^4.5.0 
  image_picker: ^0.8.5+3
  timezone: ^0.9.2
  shared_preferences: ^2.2.2
  pedometer: ^4.0.1
  fl_chart: ^0.65.0 
  provider: ^6.0.3  
  intl: ^0.19.0
  csv: ^5.0.2
  easy_localization: ^3.0.3
  url_launcher: ^6.2.3
  font_awesome_flutter: ^10.6.0
  http: ^0.13.6
  health: ^12.1.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/login.jpeg
    - assets/images/app_icon.png
    - assets/images/home.png
    - assets/images/Login.jpg
    - assets/images/SignUp.png
    - assets/images/dashboardbackground.png
    - assets/lang/en.json
    - assets/lang/ne.json
    

 
   
    
